# Generated by Django 2.1.2 on 2019-04-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('League', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('Currency', models.CharField(max_length=100)),
                ('PriceCurrency', models.CharField(max_length=100)),
                ('Value', models.FloatField()),
                ('CurrencyID', models.IntegerField()),
            ],
        ),
    ]
