<<<<<<< HEAD
# Generated by Django 2.2.4 on 2019-08-16 19:11
=======
# Generated by Django 2.1.2 on 2019-04-04 18:52
>>>>>>> e2bf2a934fd101535a3a3f7238c42857b6893c32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('League', models.CharField(max_length=50)),
<<<<<<< HEAD
                ('date', models.CharField(max_length=50)),
=======
                ('date', models.DateField()),
>>>>>>> e2bf2a934fd101535a3a3f7238c42857b6893c32
                ('Currency', models.CharField(max_length=100)),
                ('PriceCurrency', models.CharField(max_length=100)),
                ('Value', models.FloatField()),
                ('CurrencyID', models.IntegerField()),
            ],
        ),
    ]
